const BASE_URL = "http://localhost:8080";




const USER_LOGIN_ENDPOINT = "/auth/user/login";
const USER_REGISTER_ENDPOINT = "/auth/user/register";
const USER_DATA_ENDPOINT = "/user/userdata";
const USER_INPUT_DUPLICATE_ENDPOINT = "/auth/user/check-duplicate"
const USER_COMPANY_DATA_ENDPOINT = "/user/getAllCompanies"


const COMPANY_LOGIN_ENDPONT = "/auth/company/login";
const COMPANY_REGISTER_ENDPOINT = "/auth/company/register";
const COMPANY_DATA_ENDPOINT = "/company/companydata";
const COMPANY_INPUT_DUPLICATE_ENDPOINT = "/auth/company/check-duplicate";
const COMPANY_CREATE_APPOINTMENT_ENDPOINT = "/company/addAppointment";
const COMPANY_APPOINTMENT_DATA_BY_COMPANY_ID_ENDPOINT =  "/company/getAppointmentsByCompanyId/"

export {BASE_URL, USER_LOGIN_ENDPOINT, USER_REGISTER_ENDPOINT, USER_DATA_ENDPOINT, USER_INPUT_DUPLICATE_ENDPOINT,
        COMPANY_LOGIN_ENDPONT, COMPANY_REGISTER_ENDPOINT, COMPANY_DATA_ENDPOINT, COMPANY_INPUT_DUPLICATE_ENDPOINT, USER_COMPANY_DATA_ENDPOINT, COMPANY_CREATE_APPOINTMENT_ENDPOINT,
        COMPANY_APPOINTMENT_DATA_BY_COMPANY_ID_ENDPOINT


};